export const CLUB_LOGIN_REQUEST = 'CLUB_LOGIN_REQUEST';
export const CLUB_LOGIN_SUCCESS = 'CLUB_LOGIN_SUCCESS';
export const CLUB_LOGIN_FAIL = 'CLUB_LOGIN_FAIL';
export const CLUB_LOGOUT = 'CLUB_LOGOUT';

export const CLUB_REGISTER_REQUEST = 'CLUB_REGISTER_REQUEST';
export const CLUB_REGISTER_SUCCESS = 'CLUB_REGISTER_SUCCESS';
export const CLUB_REGISTER_FAIL = 'CLUB_REGISTER_FAIL';

export const CLUB_UPDATE_REQUEST = 'CLUB_UPDATE_REQUEST';
export const CLUB_UPDATE_SUCCESS = 'CLUB_UPDATE_SUCCESS';
export const CLUB_UPDATE_FAIL = 'CLUB_UPDATE_FAIL';

export const CLUB_LIST_REQUEST = 'CLUB_LIST_REQUEST';
export const CLUB_LIST_SUCCESS = 'CLUB_LIST_SUCCESS';
export const CLUB_LIST_FAIL = 'CLUB_LIST_FAIL';
