export const EXISTINGMEMBER_LOGIN_REQUEST = 'EXISTINGMEMBER_LOGIN_REQUEST';
export const EXISTINGMEMBER_LOGIN_SUCCESS = 'EXISTINGMEMBER_LOGIN_SUCCESS';
export const EXISTINGMEMBER_LOGIN_FAIL = 'EXISTINGMEMBER_LOGIN_FAIL';
export const EXISTINGMEMBER_LOGOUT = 'EXISTINGMEMBER_LOGOUT';

export const EXISTINGMEMBER_REGISTER_REQUEST = 'EXISTINGMEMBER_REGISTER_REQUEST';
export const EXISTINGMEMBER_REGISTER_SUCCESS = 'EXISTINGMEMBER_REGISTER_SUCCESS';
export const EXISTINGMEMBER_REGISTER_FAIL = 'EXISTINGMEMBER_REGISTER_FAIL';

export const EXISTINGMEMBER_UPDATE_REQUEST = 'EXISTINGMEMBER_UPDATE_REQUEST';
export const EXISTINGMEMBER_UPDATE_SUCCESS = 'EXISTINGMEMBER_UPDATE_SUCCESS';
export const EXISTINGMEMBER_UPDATE_FAIL = 'EXISTINGMEMBER_UPDATE_FAIL';
