export const MEMBER_LOGIN_REQUEST = 'MEMBER_LOGIN_REQUEST';
export const MEMBER_LOGIN_SUCCESS = 'MEMBER_LOGIN_SUCCESS';
export const MEMBER_LOGIN_FAIL = 'MEMBER_LOGIN_FAIL';
export const MEMBER_LOGOUT = 'MEMBER_LOGOUT';

export const MEMBER_REGISTER_REQUEST = 'MEMBER_REGISTER_REQUEST';
export const MEMBER_REGISTER_SUCCESS = 'MEMBER_REGISTER_SUCCESS';
export const MEMBER_REGISTER_FAIL = 'MEMBER_REGISTER_FAIL';

export const MEMBER_UPDATE_REQUEST = 'MEMBER_UPDATE_REQUEST';
export const MEMBER_UPDATE_SUCCESS = 'MEMBER_UPDATE_SUCCESS';
export const MEMBER_UPDATE_FAIL = 'MEMBER_UPDATE_FAIL';
