export const NEWMEMBER_LOGIN_REQUEST = 'NEWMEMBER_LOGIN_REQUEST';
export const NEWMEMBER_LOGIN_SUCCESS = 'NEWMEMBER_LOGIN_SUCCESS';
export const NEWMEMBER_LOGIN_FAIL = 'NEWMEMBER_LOGIN_FAIL';
export const NEWMEMBER_LOGOUT = 'NEWMEMBER_LOGOUT';

export const NEWMEMBER_REGISTER_REQUEST = 'NEWMEMBER_REGISTER_REQUEST';
export const NEWMEMBER_REGISTER_SUCCESS = 'NEWMEMBER_REGISTER_SUCCESS';
export const NEWMEMBER_REGISTER_FAIL = 'NEWMEMBER_REGISTER_FAIL';

export const NEWMEMBER_UPDATE_REQUEST = 'NEWMEMBER_UPDATE_REQUEST';
export const NEWMEMBER_UPDATE_SUCCESS = 'NEWMEMBER_UPDATE_SUCCESS';
export const NEWMEMBER_UPDATE_FAIL = 'NEWMEMBER_UPDATE_FAIL';
